stages:
  - build
  - publish

# build stage: builds everything using trunk.
build:
  stage: build
  image: rust
  variables:
    TRUNK_VERSION: 0.16.0
  before_script:
    - rustup target add wasm32-unknown-unknown
    - wget -qO- https://github.com/thedodd/trunk/releases/download/v${TRUNK_VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf- -C /usr/local/bin
  script:
    - trunk build --release
  artifacts:
    paths:
      - dist

# pages job: compress files and publish statically.
pages:
  stage: publish
  image: alpine
  before_script:
    - apk add brotli
  script:
    - export FILES=$(ls dist/*)
    - gzip -k $FILES
    - brotli -k $FILES
    - mv dist public
    - echo '/* / 200' >> public/_redirects
  artifacts:
    paths:
      - public
  only:
    - master
