[package]
name = "diff-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
flate2 = "1.0.25"
futures = "0.3.26"
implicit-clone = "0.3.5"
itertools = "0.10.5"
log = "0.4.17"
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
similar = { version = "2.2.1", features = ["text"] }
tar = "0.4.38"
url = { version = "2.3.1", features = ["serde"] }
wasm-bindgen-futures = "0.4.34"
wasm-logger = "0.2.0"
web-sys = { version = "0.3.61", features = ["HtmlInputElement"] }
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17.0"
yew_icons = { version = "0.7.0", features = ["LucideBox", "LucideFileDiff"] }
yewprint = { version = "0.4.2" }

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
